name: Build coop

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - "**"

jobs:
    build-ubuntu:
        if: ${{ contains(github.event.head_commit.message, '[build]')}}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                sudo apt update
                sudo apt install -y build-essential git python3 libglew-dev libsdl2-dev libz-dev libcurl4-openssl-dev

            - name: Build the game
              run: make -j$(nproc)

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: sm64coopdx-ubuntu
                path: ./build/us_pc/sm64coopdx
    build:
        if: ${{ contains(github.event.head_commit.message, '[build]')}}
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                choco install mingw
                choco install git
                choco install python

            - name: Set up MSYS2
              run: |
                pacman -Syu --noconfirm
                pacman -S unzip make git mingw-w64-i686-gcc mingw-w64-x86_64-gcc mingw-w64-i686-glew mingw-w64-x86_64-glew mingw-w64-i686-SDL2 mingw-w64-i686-SDL mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL python3

            - name: Build the game
              run: |
                make -j$(nproc)

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: sm64coopdx-windows
                path: ./build/us_pc/sm64coopdx.exe
