name: Build coop

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - "**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                sudo apt update
                sudo apt install -y build-essential git python3 libglew-dev libsdl2-dev libz-dev libcurl4-openssl-dev

            - name: Build the game
              run: make -j$(nproc)
